# pandas 入门

## 2.数据结构

### Series（一维）

In [36]:
import pandas as pd

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s

a    10
b    20
c    30
dtype: int64

### DataFrame（二维）

In [37]:
data = {
    "Name": ["Tom", "Jerry", "Spike", "张三", "李四", "王五"],
    "Age": [20, 22, 24, 34, 18, 22],
    "Score": [88, 92, 95, 88, 78, 98]
}
df = pd.DataFrame(data)
# df.to_excel("test.xlsx", index=False)
df

    Name  Age  Score
0    Tom   20     88
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78
5     王五   22     98

## 3. 数据读写

In [38]:
# 读取
# df = pd.read_csv("data.csv")        # 读 CSV
# df = pd.read_excel("data.xlsx")     # 读 Excel
# df = pd.read_json("data.json")      # 读 JSON

In [39]:
# 保存
# df.to_csv("out.csv", index=False)
# df.to_excel("out.xlsx", index=False)

## 4. 查看数据

In [40]:
df.head(5)  # 前5行

    Name  Age  Score
0    Tom   20     88
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78

In [41]:
df.tail(5)  # 后5行

    Name  Age  Score
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78
5     王五   22     98

In [42]:
df.shape  # 行数和列数

(6, 3)

In [43]:
df.info()  # 列信息+数据类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Score   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes

In [44]:
df.describe()    # 数值统计描述

             Age      Score
count   6.000000   6.000000
mean   23.333333  89.833333
std     5.609516   6.997619
min    18.000000  78.000000
25%    20.500000  88.000000
50%    22.000000  90.000000
75%    23.500000  94.250000
max    34.000000  98.000000

## 5. 数据选择与过滤

### 按列

In [45]:
# 按列
print('取一列（Series）\n', df["Name"])  # 取一列（Series）
df[["Name", "Score"]]  # 取多列（DataFrame）

取一列（Series）
 0      Tom
1    Jerry
2    Spike
3       张三
4       李四
5       王五
Name: Name, dtype: object

    Name  Score
0    Tom     88
1  Jerry     92
2  Spike     95
3     张三     88
4     李四     78
5     王五     98

### 按行

In [46]:
# 按行
df.loc[0]  # 按索引标签

Name     Tom
Age       20
Score     88
Name: 0, dtype: object

In [47]:
df.iloc[0]  # 按行号

Name     Tom
Age       20
Score     88
Name: 0, dtype: object

### 条件筛选

In [48]:
df[df['Age'] > 21]

    Name  Age  Score
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
5     王五   22     98

In [49]:
df[(df["Age"] > 21) & (df["Score"] > 90)]

    Name  Age  Score
1  Jerry   22     92
2  Spike   24     95
5     王五   22     98

## 6. 数据清洗

### 缺失值

In [50]:
df.isna().sum()  # 查看缺失值

Name     0
Age      0
Score    0
dtype: int64

In [51]:
df.dropna()  # 删除含有缺失值的行

    Name  Age  Score
0    Tom   20     88
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78
5     王五   22     98

In [52]:
df.fillna(0)  # 用 0 填充缺失值

    Name  Age  Score
0    Tom   20     88
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78
5     王五   22     98

### 重复值

In [53]:
df.duplicated()  # 查找重复行

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [54]:
df.drop_duplicates()  # 删除重复行

    Name  Age  Score
0    Tom   20     88
1  Jerry   22     92
2  Spike   24     95
3     张三   34     88
4     李四   18     78
5     王五   22     98

### 类型转换

In [55]:
df["Age"] = df["Age"].astype(float)

## 7. 增删改列

In [56]:
df["Gender"] = ["M", "M", "M", "M", "M", "F"]  # 添加列

In [57]:
new_df = df.drop(["Gender", "Score"], axis=1)  # 删除列
new_df

    Name   Age
0    Tom  20.0
1  Jerry  22.0
2  Spike  24.0
3     张三  34.0
4     李四  18.0
5     王五  22.0

In [58]:
new_df = df.rename(columns={"Name": "姓名"})
new_df

      姓名   Age  Score Gender
0    Tom  20.0     88      M
1  Jerry  22.0     92      M
2  Spike  24.0     95      M
3     张三  34.0     88      M
4     李四  18.0     78      M
5     王五  22.0     98      F

## 8. 排序与索引

In [59]:
df.sort_values("Age", ascending=False)  # 按 Age 排序

    Name   Age  Score Gender
3     张三  34.0     88      M
2  Spike  24.0     95      M
1  Jerry  22.0     92      M
5     王五  22.0     98      F
0    Tom  20.0     88      M
4     李四  18.0     78      M

In [60]:
df.set_index("Name")  # 设置索引

        Age  Score Gender
Name
Tom    20.0     88      M
Jerry  22.0     92      M
Spike  24.0     95      M
张三     34.0     88      M
李四     18.0     78      M
王五     22.0     98      F

In [61]:
df.reset_index()  # 重置索引

   index   Name   Age  Score Gender
0      0    Tom  20.0     88      M
1      1  Jerry  22.0     92      M
2      2  Spike  24.0     95      M
3      3     张三  34.0     88      M
4      4     李四  18.0     78      M
5      5     王五  22.0     98      F

## 9. 分组与聚合

In [62]:
df.groupby("Gender")["Score"].mean()   # 按性别求平均分

Gender
F    98.0
M    88.2
Name: Score, dtype: float64

In [63]:
df.groupby("Gender").agg({"Age":"mean","Score":"max"})

         Age  Score
Gender
F       22.0     98
M       23.6     95

## 10. 合并与连接

In [64]:
# pd.concat([df1, df2])                   # 行拼接
# pd.merge(df1, df2, on="id")             # 按列合并（类似 SQL join）

## 11. 常用统计函数

In [65]:
df["Score"].mean()   # 平均值

89.83333333333333

In [66]:
df["Score"].sum()    # 总和

539

In [67]:
df["Score"].max()    # 最大值

98

In [68]:
df["Score"].min()    # 最小值

78

In [69]:
df["Score"].value_counts()   # 计数统计

Score
88    2
92    1
95    1
78    1
98    1
Name: count, dtype: int64

学习 pandas 可以按这条线索走：

数据结构：Series 和 DataFrame

数据读写：CSV、Excel、JSON

数据查看：head、info、describe

数据选择：loc、iloc、条件过滤

数据清洗：缺失值、重复值、类型转换

数据操作：新增/删除列、排序、分组、合并

统计分析：mean、sum、value_counts

可视化：plot、hist、scatter